name: Publish Release
on:
  push:
    branches: [main]
    tags:
      - '^[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: 1
      - name: Install Package dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Check if it is prerelease
        id: prerelease-check
        run: |
          echo "::set-output name=version::$(git describe --tags --abbrev=0)"
          echo "::set-output name=tag::$(git describe --tags --abbrev=0 | sed -E 's/[0-9\.]+(-([a-zA-Z0-9]+))/\2/gm;t;d')"
      - name: Create GH Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: ${{ steps.prerelease-check.outputs.tag != '' }}
          title: ${{ steps.prerelease-check.outputs.version }}
          files: |
            dist/**
